# Configuração da API Banco Digital - db.tec.br
spring:
  application:
    name: db-banco-digital

  datasource:
    url: jdbc:postgresql://localhost:5432/banco_digital
    username: db_user
    password: db_secret
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: America/Sao_Paulo

server:
  port: 8081

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    disable-swagger-default-url: true
    use-root-path: false

logging:
  level:
    br.tec.db: INFO
    org.hibernate.SQL: WARN
